Import('env')

import os

include = env.Install('include', ['#include/fstrace.h'])
lib = env.Install('lib', ['../../src/libfstrace.a'])
env.Command('etc/fstracecheck.py', [], 'ln -sf ../bin/fstracecheck $TARGET')
fstracecheck = env.Install('bin', ['#bin/fstracecheck','#bin/fstracecheck2'])

if env["HOST_ARCH"] == env["ARCH"]:
    env.Alias(
        'install', env.Install(os.path.join(env['PREFIX'], 'include'), include),
    )
    env.Alias('install', env.Install(os.path.join(env['PREFIX'], 'lib'), lib))
    env.Alias(
        'install', env.Install(os.path.join(env['PREFIX'], 'bin'), fstracecheck)
    )

env.FSEnvInstallCommonLibConfig()
